credentials:
  usernames:
    admin:
      email: admin@example.com
      failed_login_attempts: 0
      first_name: Administrator
      last_name: User
      logged_in: false
      name: Administrator
      password: $2b$12$5PEbZR.UzVo9awQQxwf2b.HggFGB22co3GReicvWazmW4WeF8p.U2
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
